import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import "./styles/style.css"
import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${roboto.className} h-full antialiased`}
      
    >
      
      <body className="min-h-full">
        <Navbar />
        {children}
        <Footer />
        </body>
    </html>
  );
}
